server:
  port: 9001
spring:
  application:
    name: simple-pay-app-notify
  cloud:
    consul:
      host: 192.168.178.128
      port: 8500
      discovery:
        serviceName: ${spring.application.name} # 注册到consul的服务名称
        prefer-ip-address: true
        health-check-interval: 3s
        health-check-path: /consul/health
  rabbitmq:
    host: 192.168.178.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

notify:
  interval-time: 0,1,2,3,4
  success-value: success
  