server:
  port: 9001
spring:
  application:
    name: simple-pay-service-notify
  cloud:
    consul:
      host: 192.168.178.128
      port: 8500
      discovery:
        serviceName: ${spring.application.name} # 注册到consul的服务名称
        prefer-ip-address: true
        health-check-interval: 3s
        health-check-path: /consul/health
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.178.128:3306/simple_pay_service_notify?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      max-active: 100
      initial-size: 2
      min-idle: 2
      max-wait: 60000
      validation-query: select 'x'
  rabbitmq:
    host: 192.168.178.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
mybatis:
  mapperLocations: classpath:/mapper/*.xml


notify:
  exchange: 
    simple.pay.notify.exchange
  routingkey:
    simple.pay.notify.*
  queueKey:
    simple.pay.notify.queue